### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by gerald-dotcom** [flekschas/svelte-simple-modal#10]
(!) Plugin svelte: <Component/> will not be reactive if Component changes. Use <svelte:component this={Component}/> if you want this reactivity.
node_modules\svelte-simple-modal\src\Modal.svelte
217:           {/if}
218:           <div class="content" style={cssContent}>
219:             <Component {...props}/>
                 ^
220:           </div>
221:         </div>

Is it safe to ignore?

**Comment by flekschas** [comment]
Thanks for reporting! I've never seen this before. Do you see this in the [REPL](https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4?version=3.18.2)? Do you have a Which version are you using? Maybe things changed recently in Svelte.

**Comment by flekschas** [comment]
Fixed in #11

**Comment by flekschas** [comment]
Fix is available in [v0.3.1](https://www.npmjs.com/package/svelte-simple-modal)

Thanks again for reporting! Much appreciated 👏
