### ISSUE TITLE
Support Svelte v4 in peerDepenencies

### ISSUE THREAD

**Issue by mcmxcdev** [flekschas/svelte-simple-modal#100]
Svelte v4 has just been released: https://github.com/sveltejs/svelte/releases/tag/svelte%404.0.0

It would be great to test and then update the allowed `peerDepenencies` range to include v4: https://github.com/flekschas/svelte-simple-modal/blob/master/package.json#L39-L41

**Comment by flekschas** [comment]
Good idea! I'll try to do some testing over the next days. If you have the time to also give it a try with svelte v4 that'd be much appreciated.

**Comment by flekschas** [comment]
Here's a PR fixing the peer dependency: https://github.com/flekschas/svelte-simple-modal/pull/101

If you have the chance, please give it a test.

**Comment by mcmxcdev** [comment]
Hey @flekschas, I tested my application with the latest commit of the Svelte 4 PR and it works great!

![image](https://github.com/flekschas/svelte-simple-modal/assets/16797721/829973dc-7dbc-44b6-ac11-81364a3abcce)

I would say the PR is ready to get merged :smile:
