### ISSUE TITLE
Internal server error: Failed to resolve entry for package "svelte-simple-modal". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "svelte-simple-modal" package

### ISSUE THREAD

**Issue by FluffyDiscord** [flekschas/svelte-simple-modal#107]
I had to update the plugin today, since I have been using fork, which got removed.

The following line of code throws exception an no longer works.
```svelte
<script lang="ts">
    import {bind} from "svelte-simple-modal"
</script
```

vite: 4.0.4
svelte: 3.55.1
svelte-simple-modal: 1.6.1
@sveltejs/vite-plugin-svelte: 1.0.0-next.42
svelte-preprocess: 4.10.6

vite.config.js
```js
import {defineConfig} from "vite"
import { svelte } from "@sveltejs/vite-plugin-svelte"
import sveltePreprocess from "svelte-preprocess"

export default defineConfig({
    plugins: [
        svelte({
            preprocess: [
                sveltePreprocess({ typescript: true }),
            ],
            hot: {
                preserveLocalState: true,
                optimistic: true
            },
        }),
    ],
    server: {
        port: 3000,
    },
    build: {
        rollupOptions: {
            input: {
                app: "./assets/app.ts",
            },
        },
    },
    resolve: {
        dedupe: ["svelte",  "svelte/transition", "svelte/internal"],
        alias: [
            {
                find: /^~.+/,
                replacement: (val) => {
                    return val.replace(/^~/, "");
                },
            },
        ],
    },
});
```

version 1.5.1 works fine

**Comment by sirinsidiator** [comment]
I just hit the same problem after updating a project of mine and it looks like the latest version limits the exported files in `package.json` via the `exports` field, but does not include the file specified in `types`. After changing it to the following, it works for my case:
```json
  "exports": {
    ".": {
      "svelte": "./src/index.js",
      "types": "./types/index.d.ts"
    }
  },
```

**Comment by flekschas** [comment]
@sirinsidiator thanks for taking a stab at it! Do you want to create a PR with your change? Happy to get it merged asap

**Comment by sirinsidiator** [comment]
I don't have the project checked out (only stabbed around in the node_modules folder), so it would be faster if you could just add the line yourself.

**Comment by flekschas** [comment]
Adressed in v1.6.2 as suggested by @sirinsidiator. Closing this but please reopen if it's still an issue.
