### ISSUE TITLE
how to use in svelte5?

### ISSUE THREAD

**Issue by Neptunium1129** [flekschas/svelte-simple-modal#113]
https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/2540ebd9-e07e-454e-98ff-0ddb47064dc4)

App.svelte
```<script>
  import { writable } from 'svelte/store';
	import { mount } from 'svelte';
  import Modal, { bind } from 'svelte-simple-modal';
  import Popup from './Popup.svelte';
  const modal = writable(null);

  const showModal = () => modal.set(bind(Popup, { message: "It's a modal!" }));
</script>

<Modal show={$modal}>
  <button onclick={showModal}>Show modal</button>
</Modal>
```

Popup.svelte
```
<script>
  export let message = 'Hi';
</script>

<p>🎉 {message} 🍾</p>
```

**Comment by flekschas** [comment]
The library is not yet tested in svelte v5. Looks like they introduced a breaking change in v5. Please go ahead and propose an ideally backwards compatible fix if you're free.

**Comment by Neptunium1129** [comment]
> The library is not yet tested in svelte v5. Looks like they introduced a breaking change in v5. Please go ahead and propose an ideally backwards compatible fix if you're free.

-- https://github.com/sveltejs/svelte/issues/11472


I tried to change a new component to use Svelte 5 Mount command , but I failed. There are a lot of changes.

I'm thinking of leaving svelte...

**Comment by dummdidumm** [comment]
From https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes :

> If this component is not under your control, you can use the `legacy.componentApi` compiler option for auto-applied backwards compatibility (note that this adds a bit of overhead to each component).

In other words add a `svelte.config.js` with
```js
export default {
  compilerOptions: {
    legacy: { componentApi: true }
  }
}
```

This makes it backwards compatible.

**Comment by Neptunium1129** [comment]
> From https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes :
> 
> > If this component is not under your control, you can use the `legacy.componentApi` compiler option for auto-applied backwards compatibility (note that this adds a bit of overhead to each component).
> 
> In other words add a `svelte.config.js` with
> 
> ```js
> export default {
>   compilerOptions: {
>     legacy: { componentApi: true }
>   }
> }
> ```
> 
> This makes it backwards compatible.

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/227918d5-5886-498c-a8eb-a107528b65b7)

after legacy setting

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/d5027a66-1c6f-4e02-ae06-1ba4484dbde6)

**Comment by Neptunium1129** [comment]
change bind function source 

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/d0f7cb3d-6556-4324-bebe-9c935f452e9f)

```
export function bind(Component, props = {}) {
      return function ModalComponent(options) {
        /* let app = new Component({
        ...options,
        props: {
          ...props,
          ...options.props,
        },
        }) */
        let cmpData = {
          ...options,
          props: {
            ...props,
            ...options.props,
          },
          target: document.body
        };

        let component = svelte.mount(Component, cmpData);
        debugger;
        return component;
      };
    }
```

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/3dfafba8-c895-490e-b406-2bb0387e9d85)

i think ctx object missing on mount function

svelte4
![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/ee5c1da1-e8a3-4a93-9b85-cd759910ab1f)


svelte 5
![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/a64cb90d-e5cc-42f5-822f-bbe65e9c7e49)

**Comment by Neptunium1129** [comment]
edit source same.

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/29722911-4611-41f3-a1d9-30279d67b0fa)

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/d3ce1383-a7be-4337-a9bf-9bde94f4c875)

**Comment by Neptunium1129** [comment]
change new Component code 

-- svelte4
```
return new Component({
           ...options,
           props: {
             ...props,
             ...options.props,
           },
         });
```

-- svelte5
```
return mount(Component,{
           ...options,
           props: {
             ...props,
             ...options.props,
           },
           target : options.parentNode  
         });
```

![image](https://github.com/flekschas/svelte-simple-modal/assets/32185134/b9c534b8-c332-4a65-ad59-ea0a444c30fe)

**Comment by flekschas** [comment]
Cool thanks! I'll wait to cutting a new release until Svelte v5 is released. Hopefully there's a backward compatible way to support Svelte v4 and v5.
