### ISSUE TITLE
Is the wrapping div necessary?

### ISSUE THREAD

**Issue by jdevine** [flekschas/svelte-simple-modal#12]
This is a great component, but wrapping the entire app in extra divs messes up my css layout. Is there any reason it's needed? I deleted the div for my app, and it seems to work fine.

**Comment by flekschas** [comment]
Thanks for bringing this up!

> wrapping the entire app in extra divs messes up my css layout

Are you referring to the outermost div element?

> Is there any reason it's needed? I deleted the div for my app, and it seems to work fine.

You're right, it might not be needed but I want to do some more tests before removing it.

I've created a test environment: https://svelte.dev/repl/c052a22c9f044d0b8a10a7fb9e4a9693?version=3.20.1

**Comment by flekschas** [comment]
Thanks @jdevine! After testing I couldn't find a reason why the div was necessary. Version `0.4.1` removes it.
