### ISSUE TITLE
Maybe a useless line

### ISSUE THREAD

**Issue by frederikhors** [flekschas/svelte-simple-modal#13]
Is this line useful?

https://github.com/flekschas/svelte-simple-modal/blob/master/src/Modal.svelte#L80

**Comment by flekschas** [comment]
Do you mind elaborating a little bit why you added this issue? Escape can be used to trigger other actions (e.g., canceling a browser dialog) and this line ensures that the default behavior is not triggered so that only the modal is closed.

**Comment by frederikhors** [comment]
There is no "event" in that scope. Am I wrong?

**Comment by flekschas** [comment]
Good catch! However, the `event` object is still accessible. Frankly speaking, I am not sure how or why. Anyway, I'll explicitly expose the event object in the next release.
