### ISSUE TITLE
Can't get it to work in sapper

### ISSUE THREAD

**Issue by StartMeUpLille** [flekschas/svelte-simple-modal#14]
Hi there.

I just can't get the popup to appear. Here's what I've done in SAPPER

- ```npm install -D svelte-simple-modal```

- created and copy pasted the ```Content.svelte``` and ```Surprise.svelte``` in the ```components``` folder, same as in the README

-  in routes/index.svelte,  
``` 
<script>
import Content from '../components/Content.svelte';
import Modal from 'svelte-simple-modal';
</script>
<Modal>
  <Content />
</Modal>
```
- and finally set the ```dedupe``` option of ```rollup-plugin-node-resolve```

The button is there but when I click it, the popup doesn't show up.

Do you think I missed something in my configuration ? I also tried with moving Content.svelte and Surprise.svelte in the routes folder, with no success.

Thanks in advance if you can help me on this

**Comment by flekschas** [comment]
Do you see any errors in the web dev console? I haven't really used Sapper and without seeing the code it's hard to tell why nothing appears. Do you have a live example or could you copy show the content of `Content.svelte` and `Surprise.svelte`

**Comment by StartMeUpLille** [comment]
Hi @flekschas 

Everything is local on my machine. 
When I do npm run dev, the server runs normally, there's no error thrown in in the dev console. I also checked google chrome console and nothing shows up when I click the button. It doesn't break anything, as if the js animation didn't exist.

Content.svelte and Surprise.svelte are copy pasted from your README.

My problem is I'm too new to node and js frameworks to be able to trace the problem.
Maybe you could try yourself in sapper your Show Me A Surprise button, I think I did everything correctly like in your instructions for svelte (but applied to sapper for some paths).

Thanks for your reply

**Comment by flekschas** [comment]
If you don't see any errors I suspect it's an issue displaying the popup dialog or the dialog is never properly triggered. A simple thing you to test the latter is to register a `console.log` using the `onOpened` event handler as follows:

```javascript
open(Surprise, { message: "It's a popup with long text!" }, { onOpened: () => { console.log('Popup dialog opened'); } });
```

If you see the log message in the web dev console but you don't see the popup then I would inspect the DOM to see if you can find the modal div element.

**Comment by StartMeUpLille** [comment]
Thank you very much for the tip. I will give it a try and let you know.
Thanks

**Comment by StartMeUpLille** [comment]
Hi
I tried to install svelte on a fresh new seperate install and it's working now. The thing is I don't see what is different from my previous install.
Anyway, thanks for your help. I'll redevelop my app from scratch !

**Comment by flekschas** [comment]
I am glad to hear it's working now and sorry for the inconvenience. It might have been a mixup of dev JS packages.
