### ISSUE TITLE
Conflict with "const fs = require('fs');"

### ISSUE THREAD

**Issue by StartMeUpLille** [flekschas/svelte-simple-modal#15]
Hi There

Sorry to bother you again. I know now why the modal wouldn't work for me previously.

I realize that it stops working as soon as I add ```const fs = require('fs');``` inside the script tags.

The problem is I need to read and parse a local file for my app to function the way I need.

As soon as I remove ```const fs = require('fs');``` , the modal works as normal.

Maybe you want to look into it.

**Comment by flekschas** [comment]
Thanks for reporting. This sounds like a very specific issue with your app rather than the dialog modal. My guess is that internally, something with the bundling gets messed up. Without further details about your specific app, I am afraid I won't be able to help. Please provide a reproducible example and I can take a look. Also, did you test https://github.com/flekschas/svelte-simple-modal/issues/14#issuecomment-628774181?

**Comment by StartMeUpLille** [comment]
Hi @flekschas 
Thanks.
yes I tested https://github.com/flekschas/svelte-simple-modal/issues/14#issuecomment-628774181 but couldn't get anything in the console, so I decided to restart from scratch until I realised it was due to the node file system in my case.
I'll see to share a github repo for you to see what's wrong.

**Comment by StartMeUpLille** [comment]
Hi again @flekschas 
Here's a repo to see the problem:
https://github.com/StartMeUpLille/sapper-simple-modal
The Show me a surprise button is in the home/index page

1. Go to src/routes/index.svelte
2. uncomment the lines inside the <script></script> tags to create the issue

As soon as fs is enabled, the modal stops working.

i hope this helps. I won't be able to help any further as i'm a newbie in js and all the stuff around it.

**Comment by flekschas** [comment]
Thanks a lot for sharing! I'll take a look

**Comment by flekschas** [comment]
I cloned the repo, ran `npm install`, but can't start the code with `npm run start`

```
> TODO@0.0.1 start /Users/Fritz/Code/sapper-simple-modal
> node __sapper__/build

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/Users/Fritz/Code/sapper-simple-modal/__sapper__/build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by flekschas** [comment]
`npm run dev` works. I uncommented the line to load fs and I am immediately seeing 

```
ReferenceError: require is not defined
```

in the browser's dev toolbar, which explains why the modal is not working. FYI, routing back to index is broken as well. Please let me know if I am missing something but I thin this issue is unrelated to the modal itsel.

**Comment by StartMeUpLille** [comment]
Hi @flekschas 

Thanks. I also think it's not related to your plugin as I ran into more issues of the same kind with other plugins (micromodal) that stop working when I enable fs. And also it's impossible to require another file to import variables.

It's strange as I understood it's a core default node module, and it does the job in my app. It simply causes issues to other plugins.

I will report to sapper then.

Thanks for you time. You can archive this thread

**Comment by StartMeUpLille** [comment]
Update
I got a reply from sapper's team here: https://github.com/sveltejs/sapper/issues/1205#issuecomment-629758975
I can't bring fs to the client side if I understand well. It has to stay on the node side.

**Comment by flekschas** [comment]
Yes, `fs` is a node library for accessing local files. Sapper is a web framework but browsers don't allow local file access. You need to make the file accessible on the web too. I am closing the issue now.
