### ISSUE TITLE
Using nested components

### ISSUE THREAD

**Issue by davemccrea** [flekschas/svelte-simple-modal#18]
I'm encountering a `TypeError: outros is undefined` when using a nested component.

App.svelte
```
...
<Modal>
    <Delivery />
<Modal />
```

Delivery.svelte
```
...
const { open } = getContext('simple-modal');

function showCardPickerModal() {
    open(CardPicker);
}
```

CardPicker.svelte
```
<script>
import Card from './Card.svelte
<script />

<Card />
```

Card.svelte
```
<h1>Some text</h1>
```

The modal opens, however when using the close button or clicking the background the error appears in the browser console window. All works as expected when I don't use a nested component within the CardPicker component. Is this a limitation of Svelte or svelte-simple-modal? 

Using latest Svelte and svelte-simple-modal version.

**Comment by davemccrea** [comment]
Turns out I hadn't configured Webpack properly as is written on the README. Working as expected now!

**Comment by flekschas** [comment]
Glad to hear it's working 🎉

**Comment by udiudi** [comment]
Hi,
sorry for hijacking this issue, but the same error with the same scenario happens to me as well, and as far as I know Webpack is configured properly (see output [here](https://gist.github.com/udiudi/1ef32ed8bbc9de55599f45c2210b168a)).

I'm using Rails with Webpacker and Svelte. Any ideas or suggestions what may be the problem? perhaps the bundle isn't configured correctly? 

Thanks

**Comment by flekschas** [comment]
Can you provide some details? At the very least, please provide the trace of the error message. My guess is that this is a webpack config issue.

**Comment by udiudi** [comment]
of course, sorry!
It happens similarly to what was described at the first post, the same error when trying to close a nested component.

Trace and the line with the error can be found [here](https://gist.github.com/udiudi/e5f524b7e57f35ef248d10aea8a358e3)

**Comment by flekschas** [comment]
Thanks!

Given that the function you're highlighting has nothing to do with svelte-simple-modal and that multiple people have the same issue with Svelte, I certain that this is a webpack-related bundling issue:

- https://github.com/sveltejs/svelte/issues/3964
- https://github.com/sveltejs/svelte/issues/3165
- https://github.com/wewowweb/laravel-mix-svelte/issues/5#issuecomment-606558622

Unfortunately, there isn't anything I can do on my end.

**Comment by udiudi** [comment]
@flekschas thank you! I'll keep looking.

**Comment by psyCodelist** [comment]
@davemccrea can you please let me know how you configured WebPack for your issue? I'm having the same issue and no luck so far. 

Many thanks...

**Comment by udiudi** [comment]
@psyCodelist this helped me resolve my issue: https://github.com/wewowweb/laravel-mix-svelte/issues/5#issuecomment-606624410
