### ISSUE TITLE
The style of the close button cannot be changed

### ISSUE THREAD

**Issue by frederikhors** [flekschas/svelte-simple-modal#20]
Is there a way to decouple the graphics from the code?

I have my own graphic style for modals and I don't want to use the one used here.

How can we do?

**Comment by flekschas** [comment]
When you say _graphics_, are you referring to the CSS? If so, did you take a look at the examples at https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4? In particular the modal that opens when you click _"Show a customized popup"_ shows how to customize the CSS.

If you're referring to something else, can you please elaborate on what you refer to as _graphics_?

**Comment by frederikhors** [comment]
Yes I mean close button for example.

Is there a way to customize it based on my own css style?

**Comment by flekschas** [comment]
Good catch. It seems like I forgot to allow customizing the CSS of the close button. I'll add a property for that.

Everything else you can customize as shown in the example. FYI, you can also create your own close button within the modal and style it however you like.

**Comment by flekschas** [comment]
I ended up having some time and added an option to style the built-in button, but unfortunately the possibilities are a bit limited as one cannot overwrite pseudo selectors for example. If you want full control over the look of the close button you can now also use a custom Svelte component by assigning it to the `closeButton` option. See https://github.com/flekschas/svelte-simple-modal#custom-close-button and https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4 for an example

**Comment by jonadeline** [comment]
Hi @flekschas,
I'm experiencing an issue with the customisation of the close button. I'm using Sapper and I installed, as recommended, your component as a dev dependency.  Everything in working as expected on my dev environnement, I can customize the close button with a dedicated component, but once builded, the close button in the modal is the default one.  Do you have any idea what could be the origin of this behavior ?

**Comment by miguelRivero** [comment]
Hi @flekschas ,
I experience the same as @jonadeline . The custom button is lost in the build version.

**Comment by flekschas** [comment]
Apologies @jonadeline and @miguelRivero for my late reply. This seems to be a different issue related to Sapper's build process. Can I ask you to open a separate issue and provide an example? Build processes are hard to debug on their own and without knowing what exactly you're doing, I am unable to help.
