### ISSUE TITLE
Custom close button doesn't work

### ISSUE THREAD

**Issue by fbinz** [flekschas/svelte-simple-modal#27]
It can not get the custom close button to work.
The reason seems to be, that `isSvelteComponent` is not true for my component.
Given the following code
```
import CloseButton from './CloseButton.svelte'
console.log(CloseButton)
```

my local svelte version prints `Proxy<CloseButton>`, whereas the version in the REPL says `CloseButton`.

Do you have an idea of how to resolve this issue?

**Comment by flekschas** [comment]
Which version of Svelte are you using? I remember there was an issue with earlier versions.

**Comment by fbinz** [comment]
I'm using the version 3.32.2.

An easy fix would be to simply not check for `isSvelteComponent`:
```
{#if state.closeButton === true}
    <svelte:component this={state.closeButton} onClose={close} />
{:else}
    <button on:click={close} class="close" style={cssCloseButton} />
{/if}
```
As far as I can see, the `isSvelteComponent` check relies on non-documented part of the API anyways or am I missing something?

**Comment by flekschas** [comment]
That could be one possible work-around yes.

In either case, if you think `isSvelteComponent` is broken, it'd be nice if you could setup a demo that reproduces the issues. I am curious to know why/when `isSvelteComponent` fails.

**Comment by fbinz** [comment]
I researched a bit more and I can reproduce it when I use the sveltejs/template-webpack. Unfortunately I'm not familiar enough with webpack or the svelte-loader to find out why this is the case...
The attached zip file contains a minimal demo project which prints `class Proxy<Test>` on the console.


[svelte-app-test.zip](https://github.com/flekschas/svelte-simple-modal/files/5966240/svelte-app-test.zip)

**Comment by fbinz** [comment]
Ok, this seems to be a problem with webpack's hot reload functionality, which seems to wrap imported objects in a Proxy. Disabling hot reload solves the problem, but is of course not a viable solution.

**Comment by flekschas** [comment]
Interesting. Thanks for finding the source of the issue.

Checking `state.closeButton` only for `true` could lead to other confusion but I agree the `isSvelteComponent` is too strict. I'll propose just checking if `state.closeButton` is a function. That seems to be the minimum requirement to be a svelte component. E.g.:

```svelte
{#if isFunction(state.closeButton)}
  <svelte:component this={state.closeButton} onClose={close} />
{:else}
  <button on:click={close} class="close" style={cssCloseButton} />
{/if}
```

**Comment by fbinz** [comment]
Yes, that looks like a good solution for now.
Maybe svelte will add something like `isSvelteComponent` in the future...
