### ISSUE TITLE
Binding modal props from the parent component

### ISSUE THREAD

**Issue by mquandalle** [flekschas/svelte-simple-modal#29]
Is it possible to use the [component `bind` feature](https://svelte.dev/tutorial/component-bindings) of Svelte with the `open(KeyPadComponent)` context API ?

**Comment by flekschas** [comment]
Sure you can do that. However, `open()` already includes `bind()`. E.g.: `open(Component, props = {})` is the same as doing `open(bind(Component, props = {}))`.

**Comment by mquandalle** [comment]
I was referring the the `bind` attribute for a component prop, eg

```svelte
<script>let pin</script>

<Keypad bind:value={pin} />
```

What if I want to put `Keypad` in a modal? Unless I miss something, it is not currently possible to do that with the `open()` API?

**Comment by flekschas** [comment]
Apologies. I thought you meant the internal bind function.

No, this is currently not possible. I don't know if it's actually possible to programmatically construct these bindings in Svelte. I know Svelte support [programmatically setting props and event listeners](https://svelte.dev/docs#$set) but bind directives I don't know. (E.g. see https://stackoverflow.com/questions/59810747/how-to-bind-svelte-dynamic-components-values)

If you know a way to programmatically set bind directive please let me know and I am happy to add support for it.
