### ISSUE TITLE
100vh height gets cut off on android browsers

### ISSUE THREAD

**Issue by austlee** [flekschas/svelte-simple-modal#40]
The modal is too tall on android browsers and gets cut off on the bottom toolbar. Restyling the window and bg from 100vh to 100% units solved the issue for me. Perhaps that should be the default behavior?

**Comment by flekschas** [comment]
Could you attach a screenshot to illustrate the issue? I don't have an android device so I can't test this but in general 100vh seems reasonable as it should literally cover 100% of the available window height.

**Comment by flekschas** [comment]
If you have the chance, can you do me a favor and test this version here:

https://svelte.dev/repl/8df637ead30740bb9e8c9022df3cc11d?version=3.38.2

This should fix the issue.
