### ISSUE TITLE
`console.log('furz')` 

### ISSUE THREAD

**Issue by seriousManual** [flekschas/svelte-simple-modal#50]
this was probably a mistake right? ;)

https://github.com/flekschas/svelte-simple-modal/blob/master/src/Modal.svelte#L180

**Comment by flekschas** [comment]
Haha good catch! Having an easteregg in the source code can hurt right? 🤔😅

Removed it via b7fbd97. Thanks for finding and reporting it.

**Comment by seriousManual** [comment]
it suddenly showed up in the console in on of our projects 🤷‍♂️
let's hope that not too many german speakers saw your little easteregg 🤭

**Comment by flekschas** [comment]
The good thing is it made me check the ESLint rules again. I thought I already forbid `console.log` statements to be committed but it turns out I did not. Oh well, now they are forbidden.

Apologies again, and a new version is just published that removes the log statement.

**Comment by seriousManual** [comment]
no worries!
