### ISSUE TITLE
Page scrolling to the top on load, even if an anchor is specified

### ISSUE THREAD

**Issue by mquandalle** [flekschas/svelte-simple-modal#53]
When the `Modal` component is used, the page is scrolled to the top on first load, or during in-app navigation.
This is unwanted in case we link to an anchor.

Reproduction : https://repro-svelte-simple-modal-anchor-issue-maximequandalle.vercel.app/#anchor
Source : https://github.com/mquandalle/repro-svelte-simple-modal-anchor-issue/blob/master/src/routes/index.svelte

**Comment by mquandalle** [comment]
It seems that this bug was introduced in #31.

**Comment by flekschas** [comment]
Sorry for the glitch and thanks for reporting the issue. Can you test it with the following version of the Modal?

https://svelte.dev/repl/2eb021eff87d45019549565136b0e6ed?version=3.44.1

In my local tests with your repo this fixes the issue.

**Comment by mquandalle** [comment]
Yes it fixes the issue.

The problem was indeed the reactivity of `isMounted` variable in the following block, causing `close()` to be called on mount:
https://github.com/flekschas/svelte-simple-modal/blob/43bb9c19a69965843a525289a4e0aea3a854e77d/src/Modal.svelte#L201-L219

**Comment by flekschas** [comment]
New version with a fix is out

**Comment by mquandalle** [comment]
Thank you for the quick fix!
