### ISSUE TITLE
Improper packaging 

### ISSUE THREAD

**Issue by veritem** [flekschas/svelte-simple-modal#57]
The latest version of svelte-kit warns that simple modal is improperly packaged some one might look into this.

![image](https://user-images.githubusercontent.com/53856673/146182408-0661fa97-5a7b-4ccd-b6d1-c1c91c7e4d16.png)

**Comment by flekschas** [comment]
Do you have any more information? I can't find anything helpful when searching for the error message.

**Comment by veritem** [comment]
I just updated to latest version of a svelte-kit and that error popup

**Comment by veritem** [comment]
Svelte-kit has a built-in way for building libraries  may be that's why they through that error for libraries built other ways around

**Comment by flekschas** [comment]
I'd already help if you could tell us which version of svelte kit are you are using and when this error pops up. I am not using Svelte Kit actively right now, so I don't know what packaging setting might cause this warning.

**Comment by veritem** [comment]
I'm using svelte `v3.44.2` and  svelte-kit `1.0.0-next.1` the latest version

**Comment by flekschas** [comment]
@veritem The warning should be gone in v1.1.3. If not, please reopen the ticket. Thanks for submitting the issue.
