### ISSUE TITLE
Very difficult example for understanding

### ISSUE THREAD

**Issue by IoTManagerProject** [flekschas/svelte-simple-modal#60]
Please put very very simple example how to make modal only from one file. From App.svelte. Without 3 or more files.

**Comment by flekschas** [comment]
Unfortunately, it's not possible to create an example with just one file. You need at least two files: one file for your app component and another one for the modal itself.

```svelte
<!-- App.svelte -->
<script>
  import { writable } from 'svelte/store';
  import Modal from 'svelte-simple-modal';
  import Popup from './Popup.svelte';
  const modal = writable(null);
  const showModal = () => modal.set(Popup);
</script>

<Modal show={$modal}>
  <button on:click={showModal}>Show modal</button>
</Modal>

<!-- Popup.svelte -->
<p>🎉 Hi 🍾</p>
```

Demo: https://svelte.dev/repl/6f55b643195646408e780ceeb779ac2a

**Comment by MentalGear** [comment]
Thx, would be great if this could be in the readme !!!

**Comment by aboveyunhai** [comment]
@flekschas  any particular reason why two files is needed? Is it the limitation of Svelte itself?
the two files thing is actually confusing me for a while, it would be helpful to add the line into documentation.
