### ISSUE TITLE
Make not only CSS attributes be changeable from the API but also CSS classes

### ISSUE THREAD

**Issue by Artenuvielle** [flekschas/svelte-simple-modal#62]
When using styling libraries like e.g. TailwindCSS you rather want to assign a css class like bg-thm-primary to an element like the page overlay in the background of the modal instead of setting the rgb value itself.

Example:
instead of
```
open(
    ConfirmationModal,
    {},
    {
        styleBg: {
            background: "rgba(98, 69, 180, 0.4)",
        },
        styleWindow: {
            borderRadius: "1rem",
        },
    }
);
```
I'd like to write
```
open(
    ConfirmationModal,
    {},
    {
        styleBg: "bg-thm-primary",
        styleWindow: "rounded-xl",
    }
);
```

**Comment by flekschas** [comment]
I like this idea. I believe it requires a few changes though:
1. New properties for assigning class names: `classBg`, `classWindow`, and `classContent`. I see the convenience of polymorphic APIs but it feels cleaner to separate both.
2. Potentially a new property to reset base styles. Something like `unstyled: true` maybe.

Any thoughts? Also, please feel free to take a stab at it. I am happy to a PR addressing this issue.

**Comment by flekschas** [comment]
Here's a example with TailwindCSS using the proposed `classBg`, `classWindowWrap`, `classWindow`, `classContent`, `classClose`, and `unstyled` props.

https://svelte.dev/repl/f2a988ddbd5644f18d7cd4a4a8277993

Let me know what you think.

Unfortunately, it seems like internal Svelte class names are applied always at the end, e.g., `bg-red-500 svelte-g4wg3a. So overriding style properties that are already defined via internal CSS classes (like the background color) is not possible. Instead one has to opt for defining all styles via `unstyled={true}` as shown in the linked example.

If you know around this, please let me know.

**Comment by Artenuvielle** [comment]
As described at https://svelte.dev/tutorial/classes the `class:classname={boolean}` construct is just a shorthand for `class={booalean?"classname":""}`. Therefore you could write instead of:
```
<div
    class:bg={!unstyled}
    class={state.classBg}
```
something like:
```
<div
    class:bg={!unstyled}
    class={(unstyled ? "bg ": "") + state.classBg}
```

**Comment by flekschas** [comment]
Have you tested this and can confirm that it allows overriding styles via classes? In my tests it did not but maybe I am missing something.

**Comment by Artenuvielle** [comment]
Yeah, you are right. the problem arises from the scoping in svelte leading to an increase specifity of the simple-modal css classes over global ones defined by tailwind. However, I think the idea of this adding to the simple-modal library is great anyway because one can still write custom global css classes with a higher specifity (e.g. by increasing the class name cound or using !important) and pass these from outside the modal.
