### ISSUE TITLE
Minor code improvement

### ISSUE THREAD

**Issue by justingolden21** [flekschas/svelte-simple-modal#68]
Hi, I'm wondering why on line 334 you ad `tabbable.length` since you're doing `% tabbable.length` the next line anyway, it shouldn't matter, right?

![image](https://user-images.githubusercontent.com/30274440/155023274-a52945a6-8a11-41c8-a4e2-e96561684f28.png)

https://github.com/flekschas/svelte-simple-modal/blob/master/src/Modal.svelte#L334

**Comment by justingolden21** [comment]
Oh is it to make it a positive number in the case that index was -1 before and it's shift tab?

**Comment by flekschas** [comment]
Thanks for asking. The code isn't too obvious, I agree haha.

Yeah, `-1 % 5 === -1` but we want to move the focus to a _tabbable_ element inside the modal. The `shiftKey` modification just inverses the sequence of focus elements. So in other words, when you press SHIFT and then press TAB the last tabbable element is focused first, then the second last, and so on.

But really, `tabbable.length` is only added to ensure that `index` is in `[0, tabbable.length[` (all numbers from `0` to `tabbable.length - 1`). The modulo operation only ensure this for positive numbers. Hence we need to make sure that `index` is positive before we apply the modulo.

I hope this explains it.

**Comment by justingolden21** [comment]
Yeah that makes sense; thanks for explaining!

I was just looking at the source code because I'm having trouble getting this working in my own modal haha. Your code is very well written 😄
