### ISSUE TITLE
REPL example refactoring

### ISSUE THREAD

**Issue by jutunen** [flekschas/svelte-simple-modal#7]
Hello!

I tried to refactor Content.svelte away from the REPL example:
https://svelte.dev/repl/336787f06e904d49ade249d42bdf4f51?version=3.15.0

It complains about getContext being undefined... I'm not familiar with Context API, damn.

Is it possible to use the modal more straightforwardly so that the Context-module could be merged to the App-module the way I'm trying to do?

**Comment by flekschas** [comment]
Thanks for your efforts.

I think what you're trying to do is not possible as the context is only exposed to child components but `App.svelte` is not a child of `Modal.svelte`. For more see https://svelte.dev/tutorial/context-api

If I remember correctly I tried to exactly implement simple-modal the way you are trying right now but I couldn't find a way around the context issue. If you find a way around this let me know. :)

**Comment by flekschas** [comment]
I am closing this now as I currently don't see a way to refactor `Content.svelte` away. If you find a solution, please submit a PR and I am happy to merge it!

**Comment by avimar** [comment]
I think I'm interested in the same thing.

I'd really rather not have 3 tags - the other div, the button/text for the modal, and then the modal content.
Is there any way around this?
