### ISSUE TITLE
Modal Target

### ISSUE THREAD

**Issue by Roxgame95** [flekschas/svelte-simple-modal#73]
Hi , 
how to pass component to Modal without doing it in html tags i wanna set different target separately
example of what am doing 

----------------- this will set target to both components at once ------------------------
new ModalCompo({
target: Target,
props: {
Name: Name,
},
});

------------ModalCompo Script------------
<script>
    import Modal from "svelte-simple-modal";
    import Popup from "./Content.svelte";
    export let Name = "";
 
</script>

<Modal><Popup Name={Name}/></Modal> 
------------------------------------------ 

**what i want to do  ====>**

const popupmeesage = new Popup({
target: Target,
props: {
Name: Name,
},
});

const modal = new  Modal({
target: document.body,
content: popupmeesage
});

------------------------------------------ 
Thank you

**Comment by Roxgame95** [comment]
The use case am creating chrome extension where i have to inject component inside the html body so i found the only way is to create component via script and set target but in case of your modal the content should be inside it so i wasn't able to set modal target in upper body while the content button should inside a specific place inside a table so yeah i work around to make this possible by creating many scripts it works but I don't think it is best way to do 
Also i will try to use bind idea i think it is better 

I will share code as soon as u return home

**Comment by flekschas** [comment]
Got it. Thanks for providing details. I haven't really planned for this packages to be used in such scenarios so I can't provide much help but I think your best bet at getting it to work is to use the `bind()` method.
