### ISSUE TITLE
Broken store demo when using bind

### ISSUE THREAD

**Issue by bewards** [flekschas/svelte-simple-modal#76]
demo: https://svelte.dev/repl/aec0c7d9f5084e7daa64f6d0c8ef0209?version=3.48.0

I can also produce this locally using rollup.

**Comment by bewards** [comment]
I had to set up my local the following way to get it to work:

**gulp**
``` node
rollup({
  input: "app/scripts/main.ts",
  plugins: [
    svelte({
      // Tell the svelte plugin where our svelte files are located
      include: [
        'app/**/*.svelte', 
        'node_modules/svelte-simple-modal/src/*.svelte',
      ],
```

**Modal.svelte**
`import Modal, { bind } from 'svelte-simple-modal/src/Modal.svelte';`

**Comment by bewards** [comment]
Also worth noting that importing bind in a normal typescript file (to use as a store) has the same error as the demo and my above solution doesn't work for non-svelte files

**ModalStore.ts**
```
import { writable } from 'svelte/store';
import { bind } from 'svelte-simple-modal';

const modal = writable(null);

export const showGlobalModalWithComponentProps = (component: any, props: Record<string, any>) => {
    return modal.set(bind(component, props));
}
```

**Comment by bewards** [comment]
Is there anything I can do locally to get this working, such as copying the bind function? Or are there pieces of that that rely on the the svelte file?

**Comment by flekschas** [comment]
You can use the previous version (v1.3.1). It contains a TypeScript error but you can ignore that error.

**Comment by flekschas** [comment]
I just pushed a fix to `master`. Could do me a favor and test if the latest version of `master` works for you?

**Comment by bewards** [comment]
Trying to install master via npm with the following command but it's not working:

`npm install --save flekschas/svelte-simple-modal#master --force`

**Comment by flekschas** [comment]
You can also try the following:

```
git clone https://github.com/flekschas/svelte-simple-modal
cd svelte-simple-modal
npm install
npm pack
cd ../<your-application>
npm install ../svelte-simple-modal/svelte-simple-modal-1.3.2.tgz
```

**Comment by bewards** [comment]
@flekschas confirmed master works with bind

**Comment by flekschas** [comment]
Thanks for testing! New version (v1.3.3) is out. Could you double check that it works?

**Comment by bewards** [comment]
Confirmed v1.3.3, thank you @flekschas
