### ISSUE TITLE
Option to pass reactive props to modal without using a store?

### ISSUE THREAD

**Issue by mhsdesign** [flekschas/svelte-simple-modal#79]
i have something like this:
okay i my case `something` is an exported prop which takes in some reactive data...

the proplem is in the `showPopup`, `something` is assigned and looses its reactivity.
is there a way to keep the reactivity without using stores?

```js
let something = 1;

setInterval(() => {
  something++;
}, 1000)

const showPopup = () => {
  open(Popup, { message: something });
};
```

**Comment by flekschas** [comment]
Unfortunately, this is simply not possible. `something` is a `number` and passed in by value, which does not support any reactivity. In general, Svelte stores is what you would want to use in order to enable reactivity. What is the issue with using Svelte stores?

**Comment by mhsdesign** [comment]
issue that i will need to rethink a part of my state handling.

but i will go with a $tore - thanks
