### ISSUE TITLE
Support for callbacks ( onClose, onSuccess, onCancel )

### ISSUE THREAD

**Issue by mannprerak2** [flekschas/svelte-simple-modal#8]
Any modal should support callbacks which can be used to return parameters back..
E.g callback for closing the modal, callbackSuccess, callBackCancel, callBackClosed

These can be called by the user.

**Comment by mannprerak2** [comment]
We can just provide a callback for modal being closed like this
```js
    var resolver;
    const open = (...) => new Promise(
        (resolve) => {
            resolver = resolve;
            .
            .
            .
        }
    );
    const close = (objectToReturn) => {
        Component = null;
        props = null;
        customStyleBg = {};
        customStyleWindow = {};
        customStyleContent = {};
        resolver(objectToReturn);
    };
```
I can put a PR if you like this

**Comment by flekschas** [comment]
Thanks for the feature request. I like the idea in general but could you describe each aspect in a bit more detail? I.e., what would you like to achieve / what kind of callbacks are you thinking of?

Also, it would be awesome if you could provide a simple demo by [extending the example](https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4?version=3.15.0).

Besides that I have a couple of questions:

> E.g callback for closing the modal, callbackSuccess, callBackCancel, callBackClosed
What is the difference between `callbackSuccess`, `callBackCancel`, and `callBackClosed`?

The modal currently has two modes: open and close. There is no notion of successfully closing a model, canceling a model to close it, or just closing it. It's all the same. A dialog would distinguish between the three but the modal does not.

> These can be called by the user.

A callback should be called by the library, not by the user. You can already call `open()` and `close()` programmatically. Do I misunderstand you?

What is the benefit of returning a deferred promise over a callback or `Promise.resolve()`? I guess you want to do something like:

```javascript
modal.open().then(() => { console.log('Hooray modal is closed!' });
```

I am not entirely sure, I like this approach as it's not obvious in my mind that `open()` returns a promise that resolves after the model was closed. Reading this code I would assume the promise resolves after the opening animation.

**Comment by mannprerak2** [comment]
I am a bit confused about the what constitutes a Dialog or Modal..
Basically, the idea is to be able to return some object when the Modal is closed..
Suppose I input some text from user, then I would want to receive that text when user closes the Modal..

If say we have a Modal with 2 buttons (Yes and No), user clicks on yes, no and outside the boundary then it will call Succes, Close and Cancel was callbacks respectively.

But i suppose below is the least confusing option and is also flexible

> We can just provide a callback for modal being closed like this
> 
> ```js
>     var resolver;
>     const open = (...) => new Promise(
>         (resolve) => {
>             resolver = resolve;
>             .
>             .
>             .
>         }
>     );
>     const close = (objectToReturn) => {
>         Component = null;
>         props = null;
>         customStyleBg = {};
>         customStyleWindow = {};
>         customStyleContent = {};
>         resolver(objectToReturn);
>     };
> ```
> 
> I can put a PR if you like this

I have infact used this approach in my own project.

**Comment by mannprerak2** [comment]
We can also pass a callback, instead of using promises
 ```js
open(..., onClosed:(obj)=>{
// obj is returned using close method
// and may be null
})
```

**Comment by flekschas** [comment]
Sorry for the delay.

> I am a bit confused about what constitutes a Dialog or Modal.

You're right. This is a fault on my end. I guess _svelte-simple-modal_ should really be called _svelte-simple-popup_ as I haven't implemented dialog functionality (i.e., okay, cancel buttons)

> I have in fact used this approach in my own project.

I have no doubt that you've happily used that :) but as I pointed out in my previous post, I am currently not in favor of this API. Besides your own code, where else is this pattern used? Where pattern being one calls `open()` and gets a deferred promise that is only resolved after `close()` is called.

Again, it would be super helpful if you could implement what you have in mind in Svelte's repl, using my demo as the starting point.

Right now you can already achieve almost everything you're asking for by implementing the necessary callbacks in the content components of the modal. See for an example: https://svelte.dev/repl/fdbb69a2c3744cfe956a370c824eb4df?version=3.15.0
The only thing that's not yet supported is to

**Comment by mannprerak2** [comment]
> Right now you can already achieve almost everything you're asking for by implementing the necessary callbacks in the content components of the modal. See for an example: https://svelte.dev/repl/fdbb69a2c3744cfe956a370c824eb4df?version=3.15.0

Yes, using this it is possible to do any kind of callback...

The idea is the same, we could provide an `onClosed` callback in the `open` method.
But yeah now that I think about it, it's easy enough to implement this

**Comment by flekschas** [comment]
I'll reopen this issue as I think an `onClose` handler would be a useful addition and it's currently not possible to implement it. I am just wondering what the most svelte-way would be to implement this.

Bootstrap seems to use custom events (`open`, `opened`, `close`, and `closed`) instead of callbacks. Material UI seems to follow a similar approach with 2 events (`open` fired when the opening transition starts and `close` is fired after the closing transition ended)

**Comment by mannprerak2** [comment]
I don't develop for the web much, only have some experience in android and flutter..
But i suppose events are useful if you need to support different types of frameworks or when doing things in vanilla js.
As this is specifically made for svelte, a simple `onClosed` callback seems like a better option.
Also how about providing both options?

**Comment by flekschas** [comment]
It took me a bit but the modal now (v0.4.0) has support for transition event callbacks, i.e., `onOpen`, `onOpened`, `onClose`, and `onClosed`. Please see the [README](https://github.com/flekschas/svelte-simple-modal#open) and the [customized popup of the demo](https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4?version=3.20.1).
