### ISSUE TITLE
Undesirable body styling

### ISSUE THREAD

**Issue by abhijit-hota** [flekschas/svelte-simple-modal#85]
Hello, thanks for the library!

I noticed that the `body` is given certain inline style which messes my app's whole layout when the modal is open. Can I know how can I disable/override those styles within an option/prop ? I'm overriding the styles by using extra CSS.

To be precise I don't want a `position: fixed` on the body.

**Comment by flekschas** [comment]
Unfortunately, I don't know how to prevent the page in the background from scrolling and _not_ using `position: fixed`. If you know a way how to do that I am more than happy to update the modal.

For context see https://github.com/flekschas/svelte-simple-modal/issues/28

**Comment by abhijit-hota** [comment]
I see, thanks for the info. Right now, I'll just use `position: relative !important` on the body. It doesn't seem to break anything for me.

Thanks again.
