### ISSUE TITLE
Possible to fade in/out when changing content?

### ISSUE THREAD

**Issue by ajmeese7** [flekschas/svelte-simple-modal#92]
I have the contents of my modal set to a Svelte writable store that I change the value on to manipulate the contents of the modal when the user is navigating options. Is it possible to have the fade in/out transition when the contents of the modal are being modified, so there isn't such an abrupt change?

Minimal example of my setup:

```js
<script>
	import { writable } from "svelte/store";
	import Modal from "svelte-simple-modal";

	const modal = writable(null);
</script>

<Modal show={$modal} />
```

**Comment by flekschas** [comment]
My only idea on how to achieve this is by setting the modal to a component that fades between the content. However, this is outside the realm of this library so there isn't really anything I can do here. What you do within the modal component is up to you.
