### ISSUE TITLE
Is it possible to hide (close) the Modal without losing it's edited content?

### ISSUE THREAD

**Issue by forna** [flekschas/svelte-simple-modal#98]
I have a Modal with some editable fields in it.
I would like to know if it's possible to keep the modal content, so basically just hide it when the Close button is clicked.
Currently when I close and reopen the Modal the editable fields content is lost.
I cannot simply save the Modal's form content because there are some `<input type="file">` fields that cannot be instantiated again unless the user uploads the same files again. 
Thank you.

**Comment by flekschas** [comment]
There are many ways to achieve this. The easiest is to store the form content with [svelte stores](https://svelte.dev/tutorial/writable-stores).
